### ISSUE TITLE
Android back button navigates back 2 pages

### ISSUE THREAD

**Issue by vryan95** [naveasy/Naveasy#11]
When you're using the back button on android, the application navigates back 2 pages.
Naveasy is calling the navigationService GoBackAsync method in NavigatorFrameworkAppBuilder.
However, the maui app also navigates back one page resulting in going back 2 pages and the INavigatedAware methods only being called for one of the two pages.

Tried this on android 14. Able to replicate this using the Naveasy.Samples project

**Comment by naveasy** [comment]
Hi @vryan95 , I'm quite sure this is related to [this bug of .NET MAUI itself](https://github.com/dotnet/maui/issues/28446) that seems to have been fixed in the latest release.
Could you please check if you have the latest version of MAUI and try to reproduce again and let us know?

**Comment by vryan95** [comment]
Problem still exists when using 9.0.60 or 9.0.51. The bug only talks about iOS so not sure it this is completely related. I also don't have the issue in the project referenced in that bug. 
If I comment out line 25-41 in NavigatorFrameworkAppBuilder, it only goes back 1 page, but then ofcourse the navigation events aren't triggered.

**Comment by vryan95** [comment]
Workaround: removed the Android specific code from NavigatorFrameworkAppBuilder and moved it to MainActivity in Platforms/Android.
This does mean you would have to do this on every project as an extra step though.
[Example](https://github.com/vryan95/Naveasy/tree/android_back)

**Comment by ederbond** [comment]
Hi @vryan95 could you please submit a PR with your changes if it fixes the issue?

**Comment by naveasy** [comment]
Fixed in version 3.0.0
